# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IbgeBaseContinua
                                 A QGIS plugin
 Consumir o geoserviço do IBGE e adicionar ao projeto
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-03
        copyright            : (C) 2025 by Matheus Oliveira de Freitas
        email                : matheus18.1@yahoo.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IbgeBaseContinua class from file IbgeBaseContinua.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .IBGE_Base_Continua import IbgeBaseContinua
    return IbgeBaseContinua(iface)
